/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSearchComponent: typeof import('./src/components/common/AdvancedSearchComponent.vue')['default']
    BoxIcon: typeof import('./src/components/icon/BoxIcon.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardComponent: typeof import('./src/components/common/CardComponent.vue')['default']
    DropComponent: typeof import('./src/components/DropComponent.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconApps: typeof import('./src/components/icon/IconApps.vue')['default']
    IconIsaxBox11: typeof import('./src/components/icon/IconIsaxBox11.vue')['default']
    IconLayerGroup: typeof import('./src/components/icon/IconLayerGroup.vue')['default']
    IconMobile: typeof import('./src/components/icon/IconMobile.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IsaxBoxTwo: typeof import('./src/components/icon/IsaxBoxTwo.vue')['default']
    IsaxElementIcon: typeof import('./src/components/icon/IsaxElementIcon.vue')['default']
    ListCheck: typeof import('./src/components/icon/ListCheck.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OrganizationChart: typeof import('primevue/organizationchart')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMultiple: typeof import('./src/components/common/SearchMultiple.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TreeComponent: typeof import('./src/components/TreeComponent.vue')['default']
    TreePoComponent: typeof import('./src/components/TreePoComponent.vue')['default']
    VDatePicker: typeof import('./src/components/common/VDatePicker.vue')['default']
    VDateRangePicker: typeof import('./src/components/common/VDateRangePicker.vue')['default']
    VInput: typeof import('./src/components/common/VInput.vue')['default']
    VInputNumber: typeof import('./src/components/common/VInputNumber.vue')['default']
    VMultiSelect: typeof import('./src/components/common/VMultiSelect.vue')['default']
    VSelect: typeof import('./src/components/common/VSelect.vue')['default']
    VSelectAPI: typeof import('./src/components/common/VSelectAPI.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
